apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tb4wsf7si-nodejs 
  janus-idp.io/tekton: tb4wsf7si-nodejs
  backstage.io/kubernetes-id: tb4wsf7si-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tb4wsf7si-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  