apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tb4wsf7si-nodejs-gitops
  description: This is GitOps manifest for tb4wsf7si-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=tb4wsf7si-nodejs
    backstage.io/kubernetes-id: tb4wsf7si-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: tb4wsf7si-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:tb4wsf7si-nodejs
