apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tb4wsf7si-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tb4wsf7si-nodejs 
  name: tb4wsf7si-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: tb4wsf7si-nodejs 
